% Made by JH Kim (SL version)
% OLED efficiency with an EXTERNAL SCATTERING LAYER (SL) attached to the
% substrate, instead of an MLA. The SL is index-matched to the substrate
% (n_SL = n_sub = 1.51), so the only free parameters are:
%   S : scattering optical thickness (mu_s * d)
%   g : Henyey-Greenstein asymmetry parameter
%
% The SL is described by a BSDF generated by generate_SL_BSDF.m
% (Monte Carlo, same 180x90 power-fraction convention as BSDF_MLA), and the
% substrate->outcoupling recursion is identical to the MLA pipeline in
% planar_Sweep22_MLA_JH_full_lambda_modified.m.
%
% The dipole / transfer-matrix part does not depend on (S,g), so it is
% computed once and only the BSDF recursion is swept.

clc;
tic;
clear;
load('nk_JH_total.mat')
if exist('Photopic_400_800.mat','file')
    load('Photopic_400_800.mat')
end
load('BSDF_SL_S_1to15by2_G_0.5to1by0.1_nSL_151.mat')   % BSDF_SL, S_list, g_list, n_SL

wavelength=(400:800)';
wavelength_num=length(wavelength);
sin089=sind(0:89);
cos089=cosd(0:89);

emission_spectrum=spectrum.l_Irppy2acac;
emission_spectrum=emission_spectrum(1:401);
emission_spectrum=emission_spectrum/sum(emission_spectrum);

eta_rad=0.98;
horizontal_dipole_ratio=0.76;
bottom_air_refractive_index=ones(wavelength_num,1);

for i=1:wavelength_num
    spec_lambda(i,1)=emission_spectrum(i,1)/((i+wavelength(1)-1)*10^(-9));
end
if exist('V_401','var')
    V_301=V_401(1:301,1);
end

%% OLED stack (same as MLA script; last layer = substrate, n = 1.51 = n_SL)
no_bar=[ones(401,1) material.l_Ag_McPeak material.l_B3_o_JO material.l_TCTA_o_JO material.l_TCTA_B3_o_JO material.l_TAPC_o_JO material.l_HATCN material.l_TAPC_o_JO material.l_HATCN material.l_TAPC_o_JO material.l_HATCN material.l_ITO_SNU_temp 1.51*ones(401,1)];
ne_bar=[ones(401,1) material.l_Ag_McPeak material.l_B3_e_JO material.l_TCTA_e_JO material.l_TCTA_B3_e_JO material.l_TAPC_e_JO material.l_HATCN material.l_TAPC_e_JO material.l_HATCN material.l_TAPC_e_JO material.l_HATCN material.l_ITO_SNU_temp 1.51*ones(401,1)];
thickness=[100 50 25 10 47 3 47 3 47 3 150];
EML_position=4;

z0=12.5;
u_data_num=997;
max_u=3;

layer_num=size(no_bar,2);

u=[(0:u_data_num-1)/u_data_num (u_data_num+1:u_data_num*max_u)/u_data_num];
u_num=length(u);

%% dipole emission / power dissipation (computed once)
TMF_bottom=TMF_birefringence_whole(no_bar(:,EML_position:layer_num),ne_bar(:,EML_position:layer_num),[thickness(EML_position-1)-z0 thickness(EML_position:layer_num-2) 0],u,wavelength);
TMF_top=TMF_birefringence_whole(no_bar(:,EML_position:-1:1),ne_bar(:,EML_position:-1:1),[z0 thickness(EML_position-2:-1:1) 0],u,wavelength);

K_p_v=3/4*real(ne_bar(:,EML_position)./no_bar(:,EML_position)*(u.^2./sqrt(1-u.^2)).*(1+TMF_bottom.r_p).*(1+TMF_top.r_p)./(1-TMF_bottom.r_p.*TMF_top.r_p));
K_p_h=real(3./(6*(no_bar(:,EML_position)./ne_bar(:,EML_position)).^2+2)*sqrt(1-u.^2).*(1-TMF_bottom.r_p).*(1-TMF_top.r_p)./(1-TMF_bottom.r_p.*TMF_top.r_p));
K_s_h=real(3./(2*(ne_bar(:,EML_position)./no_bar(:,EML_position)).^2+6)*(1./sqrt(1-u.^2)).*(1+TMF_bottom.r_s).*(1+TMF_top.r_s)./(1-TMF_bottom.r_s.*TMF_top.r_s));

K_p_v2=K_p_v;
K_p_h2=K_p_h;
K_s_h2=K_s_h;

K_p_v2_total=K_p_v;
K_p_h2_total=K_p_h;
K_s_h2_total=K_s_h;

K_p_v3=K_p_v;
K_p_h3=K_p_h;
K_s_h3=K_s_h;

u_sub_max_p=zeros(wavelength_num,1);
u_sub_max_s=zeros(wavelength_num,1);

u_air_max_p=zeros(wavelength_num,1);
u_air_max_s=zeros(wavelength_num,1);

for i=1:wavelength_num

    if ne_bar(i,layer_num)>ne_bar(i,EML_position)
        u_sub_max_p(i)=ceil(u_data_num*ne_bar(i,layer_num)/ne_bar(i,EML_position))-1;
    else
        u_sub_max_p(i)=ceil(u_data_num*ne_bar(i,layer_num)/ne_bar(i,EML_position));
    end

    exp_phase=ones(1,u_sub_max_p(i));

    if u_sub_max_p(i)>u_data_num
        exp_phase(u_data_num+1:u_sub_max_p(i))=exp((-4*pi*no_bar(i,EML_position)*sqrt(u(u_data_num+1:u_sub_max_p(i)).^2-1)*(thickness(EML_position-1)-z0))/wavelength(i));
    end

    K_p_v2(i,1:u_sub_max_p(i))=3/8*ne_bar(i,EML_position)*no_bar(i,layer_num)/no_bar(i,EML_position)^2*sqrt(1-(ne_bar(i,EML_position)*u(1:u_sub_max_p(i))/ne_bar(i,layer_num)).^2).*exp_phase.*u(1:u_sub_max_p(i)).^2.*abs((1+TMF_top.r_p(i,1:u_sub_max_p(i))).*TMF_bottom.t_p(i,1:u_sub_max_p(i))./(1-TMF_bottom.r_p(i,1:u_sub_max_p(i)).*TMF_top.r_p(i,1:u_sub_max_p(i)))).^2./abs(1-u(1:u_sub_max_p(i)).^2);
    K_p_h2(i,1:u_sub_max_p(i))=3*sqrt((no_bar(i,layer_num)/no_bar(i,EML_position))^2*(1-(ne_bar(i,EML_position)*u(1:u_sub_max_p(i))/ne_bar(i,layer_num)).^2)).*exp_phase.*abs((1-TMF_top.r_p(i,1:u_sub_max_p(i))).*TMF_bottom.t_p(i,1:u_sub_max_p(i))./(1-TMF_bottom.r_p(i,1:u_sub_max_p(i)).*TMF_top.r_p(i,1:u_sub_max_p(i)))).^2/(12*(no_bar(i,EML_position)/ne_bar(i,EML_position))^2+4);

    if no_bar(i,layer_num)>no_bar(i,EML_position)
        u_sub_max_s(i)=ceil(u_data_num*no_bar(i,layer_num)/no_bar(i,EML_position))-1;
    else
        u_sub_max_s(i)=ceil(u_data_num*no_bar(i,layer_num)/no_bar(i,EML_position));
    end

    exp_phase=ones(1,u_sub_max_s(i));

    if u_sub_max_s(i)>u_data_num
        exp_phase(u_data_num+1:u_sub_max_s(i))=exp((-4*pi*no_bar(i,EML_position)*sqrt(u(u_data_num+1:u_sub_max_s(i)).^2-1)*(thickness(EML_position-1)-z0))/wavelength(i));
    end

    K_s_h2(i,1:u_sub_max_s(i))=3*sqrt((no_bar(i,layer_num)/no_bar(i,EML_position))^2-u(1:u_sub_max_s(i)).^2).*exp_phase.*abs((1+TMF_top.r_s(i,1:u_sub_max_s(i))).*TMF_bottom.t_s(i,1:u_sub_max_s(i))./(1-TMF_bottom.r_s(i,1:u_sub_max_s(i)).*TMF_top.r_s(i,1:u_sub_max_s(i)))).^2./((4*(ne_bar(i,EML_position)/no_bar(i,EML_position))^2+12)*abs(1-u(1:u_sub_max_s(i)).^2));

    K_p_v2_total(i,1:u_sub_max_p(i))=3/8*(u(1:u_sub_max_p(i)).^2).*real((1+TMF_bottom.r_p(i,1:u_sub_max_p(i))).*(1-conj(TMF_bottom.r_p(i,1:u_sub_max_p(i))))./sqrt(1-u(1:u_sub_max_p(i)).^2)).*abs((1+TMF_top.r_p(i,1:u_sub_max_p(i)))./(1-TMF_bottom.r_p(i,1:u_sub_max_p(i)).*TMF_top.r_p(i,1:u_sub_max_p(i)))).^2;
    K_p_h2_total(i,1:u_sub_max_p(i))=3*real((1-TMF_bottom.r_p(i,1:u_sub_max_p(i))).*(1+conj(TMF_bottom.r_p(i,1:u_sub_max_p(i)))).*sqrt(1-u(1:u_sub_max_p(i)).^2)).*abs((1-TMF_top.r_p(i,1:u_sub_max_p(i)))./(1-TMF_bottom.r_p(i,1:u_sub_max_p(i)).*TMF_top.r_p(i,1:u_sub_max_p(i)))).^2/(12*(no_bar(i,EML_position)/ne_bar(i,EML_position))^2+4);
    K_s_h2_total(i,1:u_sub_max_s(i))=3*real((1+TMF_bottom.r_s(i,1:u_sub_max_s(i))).*(1-conj(TMF_bottom.r_s(i,1:u_sub_max_s(i))))./sqrt(1-u(1:u_sub_max_s(i)).^2)).*abs((1+TMF_top.r_s(i,1:u_sub_max_s(i)))./(1-TMF_bottom.r_s(i,1:u_sub_max_s(i)).*TMF_top.r_s(i,1:u_sub_max_s(i)))).^2/(4*(ne_bar(i,EML_position)/no_bar(i,EML_position))^2+12);

    K_p_v3(i,:)=K_p_v2(i,:);
    K_p_h3(i,:)=K_p_h2(i,:);
    K_s_h3(i,:)=K_s_h2(i,:);

    if bottom_air_refractive_index(i)>ne_bar(i,EML_position)
        u_air_max_p(i)=min(u_sub_max_p(i),ceil(bottom_air_refractive_index(i)*u_data_num/ne_bar(i,EML_position))-1);
    else
        u_air_max_p(i)=min(u_sub_max_p(i),ceil(bottom_air_refractive_index(i)*u_data_num/ne_bar(i,EML_position)));
    end

    TMF_OLED_bottom_p=TMF_birefringence_whole_p(no_bar(i,layer_num:-1:1),ne_bar(i,layer_num:-1:1),[0 thickness(layer_num-2:-1:1) 0],ne_bar(i,EML_position)*u(1:u_air_max_p(i)),wavelength(i));

    R_p_bottom=abs(TMF_OLED_bottom_p.r_p).^2;

    cos_theta_sub=sqrt(1-(ne_bar(i,EML_position)*u(1:u_air_max_p(i))/ne_bar(i,layer_num)).^2);
    cos_theta_air=sqrt(1-(ne_bar(i,EML_position)*u(1:u_air_max_p(i))/bottom_air_refractive_index(i)).^2);

    r_p=(bottom_air_refractive_index(i)*cos_theta_sub-no_bar(i,layer_num)*cos_theta_air)./(bottom_air_refractive_index(i)*cos_theta_sub+no_bar(i,layer_num)*cos_theta_air);

    R_sub_air_bottom_p=abs(r_p).^2;
    T_sub_air_bottom_p=1-R_sub_air_bottom_p;

    if bottom_air_refractive_index(i)>no_bar(i,EML_position)
        u_air_max_s(i)=min(u_sub_max_s(i),ceil(bottom_air_refractive_index(i)*u_data_num/no_bar(i,EML_position))-1);
    else
        u_air_max_s(i)=min(u_sub_max_s(i),ceil(bottom_air_refractive_index(i)*u_data_num/no_bar(i,EML_position)));
    end

    TMF_OLED_bottom_s=TMF_birefringence_whole_s(no_bar(i,layer_num:-1:1),ne_bar(i,layer_num:-1:1),[0 thickness(layer_num-2:-1:1) 0],no_bar(i,EML_position)*u(1:u_air_max_s(i)),wavelength(i));

    R_s_bottom=abs(TMF_OLED_bottom_s.r_s).^2;

    cos_theta_sub=sqrt(1-(no_bar(i,EML_position)*u(1:u_air_max_s(i))/no_bar(i,layer_num)).^2);
    cos_theta_air=sqrt(1-(no_bar(i,EML_position)*u(1:u_air_max_s(i))/bottom_air_refractive_index(i)).^2);

    r_s=(no_bar(i,layer_num)*cos_theta_sub-bottom_air_refractive_index(i)*cos_theta_air)./(no_bar(i,layer_num)*cos_theta_sub+bottom_air_refractive_index(i)*cos_theta_air);

    R_sub_air_bottom_s=abs(r_s).^2;
    T_sub_air_bottom_s=1-R_sub_air_bottom_s;

    K_p_v3(i,1:u_air_max_p(i))=K_p_v2(i,1:u_air_max_p(i)).*T_sub_air_bottom_p./(1-R_p_bottom.*R_sub_air_bottom_p);
    K_p_h3(i,1:u_air_max_p(i))=K_p_h2(i,1:u_air_max_p(i)).*T_sub_air_bottom_p./(1-R_p_bottom.*R_sub_air_bottom_p);
    K_s_h3(i,1:u_air_max_s(i))=K_s_h2(i,1:u_air_max_s(i)).*T_sub_air_bottom_s./(1-R_s_bottom.*R_sub_air_bottom_s);

end

const=(1-horizontal_dipole_ratio)*ne_bar(:,EML_position)./(wavelength.^4);
const2=horizontal_dipole_ratio*no_bar(:,EML_position).*(3+(ne_bar(:,EML_position)./no_bar(:,EML_position)).^2)./(4.*wavelength.^4);
const3=const*u;
const4=const2*u;

U_tot=2*(const3.*K_p_v+const4.*(K_p_h+K_s_h));

U_bottom_transmit_p=2*(const3.*K_p_v2+const4.*K_p_h2);
U_bottom_transmit_ph=2*(const4.*K_p_h2);
U_bottom_transmit_pv=2*(const3.*K_p_v2);
U_bottom_transmit_s=2*const4.*K_s_h2;
U_bottom_transmit=U_bottom_transmit_p+U_bottom_transmit_s;

U_bottom_transmit_total_p=2*(const3.*K_p_v2_total+const4.*K_p_h2_total);
U_bottom_transmit_total_s=2*const4.*K_s_h2_total;
U_bottom_transmit_total=U_bottom_transmit_total_p+U_bottom_transmit_total_s;

U_bottom_transmit_thick_p=2*(const3.*K_p_v3+const4.*K_p_h3);
U_bottom_transmit_thick_ph=2*(const4.*K_p_h3);
U_bottom_transmit_thick_pv=2*(const3.*K_p_v3);
U_bottom_transmit_thick_s=2*const4.*K_s_h3;
U_bottom_transmit_thick=U_bottom_transmit_thick_p+U_bottom_transmit_thick_s;

const3=repmat(const,1,u_num);
const4=repmat(const2,1,u_num);

K_bottom_transmit_p=const3.*K_p_v2+const4.*K_p_h2;
K_bottom_transmit_s=const4.*K_s_h2;
K_bottom_transmit=K_bottom_transmit_p+K_bottom_transmit_s;

K_bottom_transmit_thick_p=const3.*K_p_v3+const4.*K_p_h3;
K_bottom_transmit_thick_s=const4.*K_s_h3;
K_bottom_transmit_thick=K_bottom_transmit_thick_p+K_bottom_transmit_thick_s;

Power_ratio_air_matrix=zeros(wavelength_num,1);
Power_ratio_air2_matrix=zeros(wavelength_num,1);
Power_ratio_sub_matrix=zeros(wavelength_num,1);
Power_ratio_abs_matrix=zeros(wavelength_num,1);
Power_ratio_wg_matrix=zeros(wavelength_num,1);
Power_ratio_spp_matrix=zeros(wavelength_num,1);

EQE_air_matrix=zeros(wavelength_num,1);
EQE_air2_matrix=zeros(wavelength_num,1);
EQE_sub_matrix=zeros(wavelength_num,1);
EQE_abs_matrix=zeros(wavelength_num,1);
EQE_wg_matrix=zeros(wavelength_num,1);
EQE_spp_matrix=zeros(wavelength_num,1);

sumUtot=sum(U_tot,2);

Purcell_factor=sumUtot./((const+const2)*u_data_num);
eta_eff=eta_rad*Purcell_factor./(1-eta_rad+eta_rad*Purcell_factor);

emission_spectrum=emission_spectrum/sum(emission_spectrum);

emissioneta_sumUtot=emission_spectrum.*eta_eff./sumUtot;
lambdaemissioneta_sumUtot=wavelength.*emissioneta_sumUtot/sum(wavelength.*emission_spectrum);

P_air_p=zeros(wavelength_num,90);
P_air_s=zeros(wavelength_num,90);

P_sub_p=zeros(wavelength_num,90);
P_sub_s=zeros(wavelength_num,90);

const3=pi*(const+const2);
const=bottom_air_refractive_index./ne_bar(:,EML_position);
const2=bottom_air_refractive_index./no_bar(:,EML_position);

for i=1:wavelength_num

    Power_ratio_air_matrix(i)=emissioneta_sumUtot(i)*(sum(U_bottom_transmit_thick_p(i,1:u_air_max_p(i)))+sum(U_bottom_transmit_thick_s(i,1:u_air_max_s(i))));
    Power_ratio_air2_matrix(i)=emissioneta_sumUtot(i)*(sum(U_bottom_transmit_p(i,1:u_air_max_p(i)))+sum(U_bottom_transmit_s(i,1:u_air_max_s(i))));
    Power_ratio_sub_matrix(i)=emissioneta_sumUtot(i)*(sum(U_bottom_transmit_p(i,1:u_sub_max_p(i)))+sum(U_bottom_transmit_s(i,1:u_sub_max_s(i))));
    Power_ratio_abs_matrix(i)=emissioneta_sumUtot(i)*(sum(U_bottom_transmit_total_p(i,1:u_sub_max_p(i))-U_bottom_transmit_p(i,1:u_sub_max_p(i)))+sum(U_bottom_transmit_total_s(i,1:u_sub_max_s(i))-U_bottom_transmit_s(i,1:u_sub_max_s(i))));
    Power_ratio_wg_matrix(i)=emissioneta_sumUtot(i)*(sum(U_bottom_transmit_p(i,u_sub_max_p(i)+1:u_data_num))+sum(U_bottom_transmit_s(i,u_sub_max_s(i)+1:u_data_num)));
    Power_ratio_spp_matrix(i)=emissioneta_sumUtot(i)*(sum(U_bottom_transmit_p(i,max(u_sub_max_p(i),u_data_num)+1:end))+sum(U_bottom_transmit_s(i,max(u_sub_max_s(i),u_data_num)+1:end)));

    EQE_air_matrix(i)=lambdaemissioneta_sumUtot(i)*(sum(U_bottom_transmit_thick_p(i,1:u_air_max_p(i)))+sum(U_bottom_transmit_thick_s(i,1:u_air_max_s(i))));
    EQE_air2_matrix(i)=lambdaemissioneta_sumUtot(i)*(sum(U_bottom_transmit_p(i,1:u_air_max_p(i)))+sum(U_bottom_transmit_s(i,1:u_air_max_s(i))));
    EQE_sub_matrix(i)=lambdaemissioneta_sumUtot(i)*(sum(U_bottom_transmit_p(i,1:u_sub_max_p(i)))+sum(U_bottom_transmit_s(i,1:u_sub_max_s(i))));
    EQE_abs_matrix(i)=lambdaemissioneta_sumUtot(i)*(sum(U_bottom_transmit_total_p(i,1:u_sub_max_p(i))-U_bottom_transmit_p(i,1:u_sub_max_p(i)))+sum(U_bottom_transmit_total_s(i,1:u_sub_max_s(i))-U_bottom_transmit_s(i,1:u_sub_max_s(i))));
    EQE_wg_matrix(i)=lambdaemissioneta_sumUtot(i)*(sum(U_bottom_transmit_p(i,u_sub_max_p(i)+1:u_data_num))+sum(U_bottom_transmit_s(i,u_sub_max_s(i)+1:u_data_num)));
    EQE_spp_matrix(i)=lambdaemissioneta_sumUtot(i)*(sum(U_bottom_transmit_p(i,max(u_sub_max_p(i),u_data_num)+1:end))+sum(U_bottom_transmit_s(i,max(u_sub_max_s(i),u_data_num)+1:end)));

    P_air_p(i,:)=const(i)*spline(ne_bar(i,EML_position)*u(1:u_air_max_p(i)),sqrt(const(i)^2-u(1:u_air_max_p(i)).^2).*K_bottom_transmit_thick_p(i,1:u_air_max_p(i)),bottom_air_refractive_index(i)*sin089)/const3(i);
    P_air_s(i,:)=const2(i)*spline(no_bar(i,EML_position)*u(1:u_air_max_s(i)),sqrt(const2(i)^2-u(1:u_air_max_s(i)).^2).*K_bottom_transmit_thick_s(i,1:u_air_max_s(i)),bottom_air_refractive_index(i)*sin089)/const3(i);

    if bottom_air_refractive_index(i)>ne_bar(i,layer_num)
        P_air_p(i,ceil(asind(ne_bar(i,layer_num)/bottom_air_refractive_index(i)))+1:90)=0;
    end

    if bottom_air_refractive_index(i)>no_bar(i,layer_num)
        P_air_s(i,ceil(asind(no_bar(i,layer_num)/bottom_air_refractive_index(i)))+1:90)=0;
    end

    % --- P_sub (extrapolation-safe, same as modified MLA script) ---
    u_data_p = u(1:u_sub_max_p(i));
    x_data_p = ne_bar(i,EML_position) * u_data_p;

    sqrt_arg_p = (ne_bar(i,layer_num)/ne_bar(i,EML_position))^2 - u_data_p.^2;
    safe_sqrt_arg_p = max(0, sqrt_arg_p);

    y_data_p = sqrt(safe_sqrt_arg_p) .* K_bottom_transmit_p(i, 1:u_sub_max_p(i));

    xq_data_p = ne_bar(i,layer_num) * sin089;

    interpolated_values_p = interp1(x_data_p, y_data_p, xq_data_p, 'spline', 0);

    P_sub_p(i,:) = (ne_bar(i,layer_num) / ne_bar(i,EML_position)) * interpolated_values_p / const3(i);

    u_data_s = u(1:u_sub_max_s(i));
    x_data_s = no_bar(i,EML_position) * u_data_s;

    sqrt_arg_s = (no_bar(i,layer_num)/no_bar(i,EML_position))^2 - u_data_s.^2;
    safe_sqrt_arg_s = max(0, sqrt_arg_s);

    y_data_s = sqrt(safe_sqrt_arg_s) .* K_bottom_transmit_s(i, 1:u_sub_max_s(i));

    xq_data_s = no_bar(i,layer_num) * sin089;

    interpolated_values_s = interp1(x_data_s, y_data_s, xq_data_s, 'spline', 0);

    P_sub_s(i,:) = (no_bar(i,layer_num) / no_bar(i,EML_position)) * interpolated_values_s / const3(i);

end

Power_ratio_air=sum(Power_ratio_air_matrix);
Power_ratio_sub=sum(Power_ratio_sub_matrix);
Power_ratio_sub_confined=Power_ratio_sub-Power_ratio_air;
Power_ratio_abs=sum(Power_ratio_abs_matrix);
Power_ratio_wg=sum(Power_ratio_wg_matrix);
Power_ratio_spp=sum(Power_ratio_spp_matrix);

EQE_air=sum(EQE_air_matrix);
EQE_sub=sum(EQE_sub_matrix);
EQE_sub_confined=EQE_sub-EQE_air;
EQE_abs=sum(EQE_abs_matrix);
EQE_wg=sum(EQE_wg_matrix);
EQE_spp=sum(EQE_spp_matrix);

P_air=P_air_p+P_air_s;
P_sub=P_sub_p+P_sub_s;
I_air=P_air.*repmat(emission_spectrum.*eta_eff./Purcell_factor,1,90);

I_air_total=sum(I_air);
I_air_total=I_air_total/I_air_total(1);

I_sub=P_sub.*repmat(emission_spectrum.*eta_eff./Purcell_factor,1,90);

I_sub_total=sum(I_sub);
I_sub_total=I_sub_total/I_sub_total(1);

EQE_factor_air=pi*sum(I_air_total.*sin089)/90;
EQE_factor_sub=pi*sum(I_sub_total.*sin089)/90;

I_FWHM=I_air(:,1);
I_FWHM=I_FWHM/max(I_FWHM);
FWHM=sum(I_FWHM>=0.5);

fprintf('\nPlanar reference (no SL):\n');
fprintf('EQE_air = %d \n', EQE_air);
fprintf('EQE_subconfined = %d \n', EQE_sub_confined);
fprintf('EQE_wg = %d \n', EQE_wg);
fprintf('EQE_spp = %d \n', EQE_spp);
fprintf('EQE_abs = %d \n', EQE_abs);
fprintf('EQE_sub = %d \n', EQE_sub);
disp('-------------------------------')

%% OLED bottom-side reflectance seen from the substrate (computed once)
TMF_OLED_bottom_p=TMF_birefringence_whole_p(no_bar(:,layer_num:-1:1),ne_bar(:,layer_num:-1:1),[0 thickness(layer_num-2:-1:1) 0],ne_bar(:,layer_num)*sin089,wavelength);
TMF_OLED_bottom_s=TMF_birefringence_whole_s(no_bar(:,layer_num:-1:1),ne_bar(:,layer_num:-1:1),[0 thickness(layer_num-2:-1:1) 0],no_bar(:,layer_num)*sin089,wavelength);

R_p_bottom=abs(TMF_OLED_bottom_p.r_p).^2;
T_p_bottom=no_bar(:,1)./no_bar(:,layer_num)*(1./cos089).*sqrt(1-(ne_bar(:,layer_num)./ne_bar(:,1)*sin089).^2).*abs(TMF_OLED_bottom_p.t_p).^2;

R_s_bottom=abs(TMF_OLED_bottom_s.r_s).^2;
T_s_bottom=no_bar(:,1)./no_bar(:,layer_num)*(1./cos089).*sqrt(1-(no_bar(:,layer_num)./no_bar(:,1)*sin089).^2).*abs(TMF_OLED_bottom_s.t_s).^2;

for i=1:wavelength_num
    T_p_bottom(i,ceil(asind(ne_bar(i,1)/ne_bar(i,layer_num)))+1:end)=0;
    T_s_bottom(i,ceil(asind(no_bar(i,1)/no_bar(i,layer_num)))+1:end)=0;
end

Transmittance=(T_p_bottom+T_s_bottom)/2;
Reflectance=(R_p_bottom+R_s_bottom)/2;

Psub_norm=I_sub.*sin089;
temp=repmat(sum(Psub_norm,2),1,90);
Psub_norm=Psub_norm./temp; clear temp;
Psub_norm(isnan(Psub_norm))=0;

ROLED=Reflectance;
P0=EQE_sub_matrix;
R_bot=repmat(ROLED,1,1,90);

R_step = 20;

%% S-g sweep over the scattering-layer BSDF
NS=length(S_list);
Ng=length(g_list);

data_matrix=zeros(NS*Ng,8);
Power_matrix=zeros(NS*Ng,1+R_step);
EQE_SL_map=zeros(NS,Ng);
Enhancement_map=zeros(NS,Ng);
I_SL_angle=zeros(NS,Ng,90);         % angle-resolved outcoupled intensity (sum over lambda)

R_index=1;

for iS=1:NS
    for ig=1:Ng

        BSDF=BSDF_SL(:,:,iS,ig);

        BSDF_R = BSDF(180:-1:91, :);        % rows: AOR, cols: AOI
        BSDF_T_total = sum(BSDF(1:90, :));
        BSDF_T = BSDF(1:90, :);

        BSDF_CE = zeros(180, 90);
        for i = 1:90
            for j = 1:180
                BSDF_CE(j,i) = BSDF(j,i)*sind(i-0.5)/sind(j-0.5); % BSDF normalization as intensity term
            end
        end
        BSDF_T_CE = BSDF_CE(1:90, :);

        R_matrix_1 = repmat(reshape(BSDF_R', 1, 90, 90), wavelength_num, 1, 1) .* R_bot;

        temp_power=zeros(wavelength_num,R_step);
        temp_power_total=zeros(wavelength_num,90,R_step);
        temp_power_total_for_CIE=zeros(wavelength_num,90,R_step);
        temp_power_30=zeros(wavelength_num,90,R_step);
        temp_power_30_sl=zeros(wavelength_num,R_step);
        power30_sl=zeros(1,R_step);
        Power=zeros(1,R_step);
        P_SL=zeros(wavelength_num,90,R_step);
        I_SL_for_CIE=zeros(wavelength_num,90,R_step);

        for j=1:R_step
            for i = 1:wavelength_num
                temp_psub = Psub_norm(i, :);
                temp_rmat = reshape(R_matrix_1(i, :, :), 90, 90);
                temp_power(i,j) = temp_psub * temp_rmat^(j-1) * BSDF_T_total';
                temp_power_total(i,:,j) = P_sub(i,:) * temp_rmat^(j-1);
                temp_power_total_for_CIE(i,:,j) = I_sub(i,:) * temp_rmat^(j-1);
                temp_power_30(i,:,j)=temp_psub*temp_rmat^(j-1)*BSDF_T;
            end
            temp_power_30_sl(:,j)=sum(temp_power_30(:,1:30,j),2);
            power30_sl(j)=temp_power_30_sl(:,j)'*P0;
            Power(j)=temp_power(:,j)'*P0;
            P_SL(:,:,j)=temp_power_total(:,:,j)*BSDF_T_CE';
            I_SL_for_CIE(:,:,j)=temp_power_total_for_CIE(:,:,j)*BSDF_T_CE';
        end

        TotalPower=sum(Power);
        Power_30_total=sum(power30_sl);

        I_SL_for_CIE_total=sum(I_SL_for_CIE,3);
        I_SL_norm=I_SL_for_CIE_total(:,1);
        I_SL_norms=I_SL_norm/max(I_SL_norm);
        FWHM_SL=sum(I_SL_norms>=0.5);

        I_SL_angle(iS,ig,:)=sum(I_SL_for_CIE_total,1);

        EQE_SL_map(iS,ig)=TotalPower;
        Enhancement_map(iS,ig)=TotalPower/EQE_air;

        data_matrix(R_index,:)=[S_list(iS),g_list(ig),FWHM_SL,EQE_air,EQE_sub,TotalPower,TotalPower/EQE_air,Power_30_total];
        Power_matrix(R_index,1)=TotalPower;
        Power_matrix(R_index,2:1+R_step)=Power;

        fprintf('S = %g, g = %g : EQE_SL = %.4f (x%.3f vs planar EQE_air = %.4f) [%d of %d]\n', ...
            S_list(iS),g_list(ig),TotalPower,TotalPower/EQE_air,EQE_air,R_index,NS*Ng);

        R_index=R_index+1;

    end
end

save('SL_sweep_result.mat','data_matrix','Power_matrix','EQE_SL_map','Enhancement_map','I_SL_angle', ...
     'S_list','g_list','n_SL','EQE_air','EQE_sub','EQE_wg','EQE_spp','EQE_abs','R_step','-v7');

%% summary plot (EQE map vs S and g)
figure;
imagesc(g_list,S_list,EQE_SL_map);
set(gca,'YDir','normal');
xlabel('g (HG asymmetry)');
ylabel('S (scattering optical thickness)');
title('EQE with scattering layer');
colorbar;

toc;
